### ISSUE TITLE
Unknown world exception on deserialize

### ISSUE THREAD

**Issue by SlimeDog** [jorisguffens/UltimateFireworkShow#1]
Spigot 1.11.2
FWS 1.0 (internally 1.0.1)
Please update to Spigot 1.11.2 (and 1.12). Or just remove serialization. It isn't necessary anyway, since only the _fade-colors_ values are serialized.

This occurs once for each frame on start-up.
> [20:10:02] [Server thread/INFO]: [FireworkShow] Enabling FireworkShow v1.0.1
[20:10:02] [Server thread/ERROR]: Could not call method 'public static org.bukkit.Location org.bukkit.Location.deserialize(java.util.Map)' of class org.bukkit.Location for deserialization
java.lang.IllegalArgumentException: unknown world
        at org.bukkit.Location.deserialize(Location.java:595) ~[spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:77) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:117) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:195) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:35) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:373) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:147) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:354) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:489) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequenceStep2(BaseConstructor.java:275) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequence(BaseConstructor.java:246) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlSeq.construct(SafeConstructor.java:470) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:373) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:147) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:354) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:489) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequenceStep2(BaseConstructor.java:275) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequence(BaseConstructor.java:246) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlSeq.construct(SafeConstructor.java:470) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:373) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:147) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:354) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:489) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:141) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:127) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:184) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at com.igufguf.fireworkshow.Main.onEnable(Main.java:68) [FireworkShow-1.0.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.11.2.jar-2017-06-07-2213:git-Spigot-3fb9445-6e3cec8]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by jorisguffens** [comment]
I didn't had much time to create my own serialization, I'll work on that later.
For now, I think the world of your fireworkshow just isn't loaded.

**Comment by SlimeDog** [comment]
Closed due to dev abandonment.
